//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace basisagent
{
    using System;
    using System.Collections.Generic;
    
    public partial class host_command
    {
        public int id { get; set; }
        public string hosttext { get; set; }
        public string hostname { get; set; }
        public string strip { get; set; }
        public string strusername { get; set; }
        public string strpassword { get; set; }
        public string strcommandpromat { get; set; }
        public string strcommand { get; set; }
        public string adapter { get; set; }
        public string os { get; set; }
    }
}
